### ISSUE TITLE
Any planned date for code and checkpoint release?

### ISSUE THREAD

**Issue by nitinmukesh** [ZichengDuan/EZIGen#1]

**Comment by ZichengDuan** [comment]
@nitinmukesh Thanks for your interest, we plan to release the code and checkpoints later this year, and an interactive GUI demo is expected to be released earlier, stay tuned for the updates :)

**Comment by nitinmukesh** [comment]
@ZichengDuan 
Looking forward.

**Comment by ZichengDuan** [comment]
@nitinmukesh The inference code and checkpoint are now released, and the training code is also coming soon.
