### ISSUE TITLE
Anyway to use fp16

### ISSUE THREAD

**Issue by nitinmukesh** [ZichengDuan/EZIGen#2]
Hello,

Thanks for releasing the code. Is there anyway to use fp16 version of models. What code changes will be required.

**Comment by ZichengDuan** [comment]
Hi, the inference is already set in fp16 precision using `torch.autocast` operation, as shown in `infer.py` line 483:
```
with torch.autocast("cuda"):
    ...
```
You can also refer to [this like](https://huggingface.co/docs/diffusers/v0.3.0/en/optimization/fp16) to try to load the model directly in fp16 mode. I have not tested it with my own machine but I presume this wouldn't be too troublesome.

**Comment by nitinmukesh** [comment]
Thank you. I will try.
The benefit of loading fp16 is for low VRAM users like the 1 I have.
torch_dtype=torch.float16, variant="fp16",

**Comment by nitinmukesh** [comment]
I made the changes and it works fine.
